---
title: "statistical analysis: t test, chi square, wilconxon rank-sum test"
author: "Angela Lee"
date: "4/19/2017"
output: html_document
---

```{r tidy dataset, include=FALSE}
library('plyr')
library('dplyr')
library('readr')
dataE = read_csv('./DataExtract.csv') #3551 x 95
head(dataE)


```
```{r}
Pat_demo = subset(dataE, select = c('patient_key','age_grpN','pdc_80_flag', 'sexN'))
Pat_demo[,1:4] = lapply(Pat_demo, as.numeric)
Pat_demo = cbind(Pat_demo, dataE$drug_class)
colnames(Pat_demo)[colnames(Pat_demo) == 'dataE$drug_class'] <-"drug_class"
head(dataE)
```


```{r demographic, echo=FALSE}
library('reshape2')

Pat_class = Pat_demo  %>%
  group_by(drug_class, pdc_80_flag) %>% tally()
Pat_class 


```


```{r patient demo- age, echo=FALSE}
Pat_class = Pat_demo %>% group_by(drug_class, pdc_80_flag, age_grpN) %>% tally()
Pat_class 
#check answers
Pat_class = Pat_demo %>% group_by(drug_class, pdc_80_flag, age_grpN) %>% 
    filter(age_grpN %in% 2) %>% tally()
Pat_class 


```
```{r}
Pat_class_m = Pat_demo %>% group_by(drug_class, pdc_80_flag, sexN) %>%
  filter(sexN %in% '1') %>% tally()
Pat_class_m

```

```{r Region, echo=FALSE}
Pat_s = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'regionN'))
Pat_r = Pat_s %>% group_by(drug_class, pdc_80_flag, regionN) %>% tally()
Pat_r
library(stats)
male = cbind(Pat_demo$sexN == '1')
dim(male)
d = data.frame( male, Pat_demo$pdc_80_flag)



```

```{r alcochol, echo=FALSE}
Pat_s = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'ALCOHOL_DRUG'))
Pat_A = Pat_s %>% group_by(drug_class, pdc_80_flag, ALCOHOL_DRUG) %>% 
      filter(ALCOHOL_DRUG %in% '1') %>% tally()
Pat_A
```
```{r asthma, echo=FALSE}
Pat_s = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'ASTHMA'))
Pat_a = Pat_s %>% group_by(drug_class, pdc_80_flag, ASTHMA) %>% filter(ASTHMA %in% '1') %>% tally()
Pat_a






```
```{r CARDIAC_ARRYTHMIA1, echo=FALSE}
Pat_c = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'CARDIAC_ARRYTHMIA'))
Pat_C = Pat_c %>% group_by(drug_class, pdc_80_flag, CARDIAC_ARRYTHMIA) %>% 
      filter(CARDIAC_ARRYTHMIA %in% '1') %>% tally()
Pat_C
```
```{r CARDIAC_VALVULAR1, echo=FALSE}
Pat_ca = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'CARDIAC_VALVULAR'))
Pat_Ca = Pat_ca %>% group_by(drug_class, pdc_80_flag, CARDIAC_VALVULAR) %>% 
      filter(CARDIAC_VALVULAR %in% '1') %>% tally()
Pat_Ca
```
```{r CEREBROVASCULAR1, echo=FALSE}
Pat_caa = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'CEREBROVASCULAR'))
Pat_Caa = Pat_caa %>% group_by(drug_class, pdc_80_flag, CEREBROVASCULAR) %>% 
      filter(CEREBROVASCULAR %in% '1') %>% tally()
Pat_Caa
```
```{r CHRONIC_KIDNEY1, echo=FALSE}
Pat_k = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'CHRONIC_KIDNEY'))
Pat_K = Pat_k %>% group_by(drug_class, pdc_80_flag, CHRONIC_KIDNEY) %>% 
      filter(CHRONIC_KIDNEY %in% '1') %>% tally()
Pat_K
```
```{r CHRONIC_PAIN_FIBRO1, echo=FALSE}
Pat_cp = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'CHRONIC_PAIN_FIBRO'))
Pat_Cp = Pat_cp %>% group_by(drug_class, pdc_80_flag, CHRONIC_PAIN_FIBRO) %>% 
      filter(CHRONIC_PAIN_FIBRO %in% '1') %>% tally()
Pat_Cp

```

```{r  CHF1, echo=FALSE}
Pat_chf = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'CHF'))
Pat_Chf = Pat_chf %>% group_by(drug_class, pdc_80_flag, CHF) %>% 
      filter( CHF %in% '1') %>% tally()
Pat_Chf

```
```{r COPD1, echo=FALSE}
Pat_copd = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'COPD'))
Pat_Copd = Pat_copd %>% group_by(drug_class, pdc_80_flag, COPD) %>% 
      filter( COPD %in% '1') %>% tally()
Pat_Copd
```
```{r DEMENTIA1, echo=FALSE}
Pat_d = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'DEMENTIA'))
Pat_D = Pat_d %>% group_by(drug_class, pdc_80_flag, DEMENTIA) %>% 
      filter( DEMENTIA %in% '1') %>% tally()
Pat_D
```
```{r DEPRESSION1, echo=FALSE}
Pat_de = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'DEPRESSION'))
Pat_De = Pat_de %>% group_by(drug_class, pdc_80_flag, DEPRESSION) %>% 
      filter( DEPRESSION %in% '1') %>% tally()
Pat_De
```

```{r DIABETES1, echo=FALSE}
Pat_di = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'DIABETES'))
Pat_Di = Pat_di %>% group_by(drug_class, pdc_80_flag, DIABETES) %>% 
      filter( DIABETES %in% '1') %>% tally()
Pat_Di
```
```{r DYSLIPIDEMIA1, echo=FALSE}
Pat_dy = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'DYSLIPIDEMIA'))
Pat_Dy = Pat_dy %>% group_by(drug_class, pdc_80_flag, DYSLIPIDEMIA) %>% 
      filter( DYSLIPIDEMIA %in% '1') %>% tally()
Pat_Dy
```
```{r EPILEPSY_SEIZURE1, echo=FALSE}
Pat_e = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'EPILEPSY_SEIZURE'))
Pat_E = Pat_e %>% group_by(drug_class, pdc_80_flag, EPILEPSY_SEIZURE) %>% 
      filter( EPILEPSY_SEIZURE %in% '1') %>% tally()
Pat_E
```
```{r HEPATITIS1, echo=FALSE}
Pat_h = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'HEPATITIS'))
Pat_H = Pat_h %>% group_by(drug_class, pdc_80_flag, HEPATITIS) %>% 
      filter( HEPATITIS %in% '1') %>% tally()
Pat_H
```
```{r HIV_AIDS1, echo=FALSE}
Pat_hiv = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'HIV_AIDS'))
Pat_Hiv = Pat_hiv %>% group_by(drug_class, pdc_80_flag, HIV_AIDS) %>% 
      filter( HIV_AIDS %in% '1') %>% tally()
Pat_Hiv
```
```{r Hypertention1, echo=FALSE}
Pat_hy = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'HYPERTENSION'))
Pat_Hy = Pat_hy %>% group_by(drug_class, pdc_80_flag, HYPERTENSION) %>% 
      filter( HYPERTENSION %in% '1') %>% tally()
Pat_Hy
```
```{r LIVER_GALLBLADDER_PANCREAS1, echo=FALSE}
Pat_l = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'LIVER_GALLBLADDER_PANCREAS'))
Pat_L = Pat_l %>% group_by(drug_class, pdc_80_flag, LIVER_GALLBLADDER_PANCREAS) %>% 
      filter( LIVER_GALLBLADDER_PANCREAS %in% '1') %>% tally()
Pat_L
```
```{r MI_CAD1, echo=FALSE}
Pat_cad = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'MI_CAD'))
Pat_Cad = Pat_cad %>% group_by(drug_class, pdc_80_flag, MI_CAD) %>% 
      filter( MI_CAD %in% '1') %>% tally()
Pat_Cad
```


```{r PARALYSIS1, echo=FALSE}
Pat_p = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'PARALYSIS'))
Pat_P = Pat_p %>% group_by(drug_class, pdc_80_flag, PARALYSIS) %>% 
      filter( PARALYSIS %in% '1') %>% tally()
Pat_P
```
```{r OSTEOARTHRITIS1, echo=FALSE}
Pat_o = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'OSTEOARTHRITIS'))
Pat_O = Pat_o %>% group_by(drug_class, pdc_80_flag, OSTEOARTHRITIS) %>% 
      filter( OSTEOARTHRITIS %in% '1') %>% tally()
Pat_O
```
```{r PEPTIC_ULCER1, echo=FALSE}
Pat_p = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'PEPTIC_ULCER'))
Pat_P = Pat_p %>% group_by(drug_class, pdc_80_flag, PEPTIC_ULCER) %>% 
      filter(PEPTIC_ULCER %in% '1') %>% tally()
Pat_P
```
```{r PERIPHERAL_VASCULAR1, echo=FALSE}
Pat_pv = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'PERIPHERAL_VASCULAR'))
Pat_Pv = Pat_pv %>% group_by(drug_class, pdc_80_flag,PERIPHERAL_VASCULAR) %>% 
      filter(PERIPHERAL_VASCULAR %in% '1') %>% tally()
Pat_Pv
```
```{r RENAL_FAILURE1, echo=FALSE}
Pat_r = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'RENAL_FAILURE'))
Pat_R = Pat_r %>% group_by(drug_class, pdc_80_flag,RENAL_FAILURE) %>% 
      filter(RENAL_FAILURE %in% '1') %>% tally()
Pat_R
```
```{r RHEUMATOLOGIC1, echo=FALSE}
Pat_rh = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'RHEUMATOLOGIC'))
Pat_Rh = Pat_rh %>% group_by(drug_class, pdc_80_flag, RHEUMATOLOGIC) %>% 
      filter(RHEUMATOLOGIC %in% '1') %>% tally()
Pat_Rh
```
```{r SLEEP_DISORDERS1, echo=FALSE}
Pat_sl = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'SLEEP_DISORDERS'))
Pat_Sl = Pat_sl %>% group_by(drug_class, pdc_80_flag, SLEEP_DISORDERS) %>% 
      filter(SLEEP_DISORDERS %in% '1') %>% tally()
Pat_Sl
```
```{r SCHIZOPHRENIA1, echo=FALSE}
Pat_sh = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'SCHIZOPHRENIA'))
Pat_Sh = Pat_sh %>% group_by(drug_class, pdc_80_flag, SCHIZOPHRENIA) %>% 
      filter(SCHIZOPHRENIA %in% '1') %>% tally()
Pat_Sh
```
```{r SMOKING1, echo=FALSE}
Pat_so = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'SMOKING'))
Pat_So = Pat_so %>% group_by(drug_class, pdc_80_flag, SMOKING) %>% 
      filter(SMOKING %in% '1') %>% tally()
Pat_So
```
```{r THYROID1, echo=FALSE}
Pat_t = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'THYROID'))
Pat_T = Pat_t %>% group_by(drug_class, pdc_80_flag, THYROID) %>% 
      filter(THYROID %in% '1') %>% tally()
Pat_T
```
```{r Solid_Tumor1, echo=FALSE}
Pat_s = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'Solid_Tumor'))
Pat_S = Pat_s %>% group_by(drug_class, pdc_80_flag, Solid_Tumor) %>% 
      filter(Solid_Tumor %in% '1') %>% tally()
Pat_S
```
```{r Metastatic1, echo=FALSE}
Pat_m = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'Metastatic'))
Pat_M = Pat_m %>% group_by(drug_class, pdc_80_flag, Metastatic) %>% 
      filter(Metastatic %in% '1') %>% tally()
Pat_M
```
```{r Leukemia_Lymphoma1, echo=FALSE}
Pat_ll = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'Leukemia_Lymphoma'))
Pat_Ll = Pat_ll %>% group_by(drug_class, pdc_80_flag, Leukemia_Lymphoma) %>% 
      filter(Leukemia_Lymphoma %in% '1') %>% tally()
Pat_Ll
```
```{r Other_Cancer1, echo=FALSE}
Pat_oc = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'Other_Cancer'))
Pat_Oc = Pat_oc %>% group_by(drug_class, pdc_80_flag, Other_Cancer) %>% 
      filter(Other_Cancer %in% '1') %>% tally()
Pat_Oc
```
```{r pre_ip_flag1, echo=FALSE}
Pat_ip = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'pre_ip_flag'))
Pat_Ip = Pat_ip %>% group_by(drug_class, pdc_80_flag, pre_ip_flag) %>% 
      filter(pre_ip_flag %in% '1') %>% tally()
Pat_Ip
```
```{r num_op1, echo=FALSE}
Pat_op = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'num_op'))
Pat_Op = Pat_op %>% group_by(drug_class, pdc_80_flag, num_op) %>% 
      filter(num_op %in% '1') %>% tally()
Pat_Op
```
```{r pre_er_flag1, echo=FALSE}
Pat_er = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'pre_er_flag'))
Pat_Er = Pat_er %>% group_by(drug_class, pdc_80_flag, pre_er_flag) %>% 
      filter(pre_er_flag %in% '1') %>% tally()
Pat_Er
```
```{r}
head(dataE)
```
```{r post_ip_flag1, echo=FALSE}
Pat_pip = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'post_ip_flag'))
Pat_Pip = Pat_pip %>% group_by(drug_class, pdc_80_flag, post_ip_flag) %>% 
      filter(post_ip_flag %in% '1') %>% tally()
Pat_Pip
```
```{r num_op_post1, echo=FALSE}
Pat_pop = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'num_op_post'))
Pat_Pop = Pat_pop %>% group_by(drug_class, pdc_80_flag, num_op_post) %>% 
      filter(num_op_post %in% '1') %>% tally()
Pat_Pop
```
```{r post_er_flag1, echo=FALSE}
Pat_per = subset(dataE, select = c('patient_key','drug_class','pdc_80_flag', 'post_er_flag'))
Pat_Per = Pat_per %>% group_by(drug_class, pdc_80_flag, post_er_flag) %>% 
      filter(post_er_flag %in% '1') %>% tally()
Pat_Per
```

```{r}

AD = subset(dataE, grepl('ANTIDIABETICS', dataE$drug_class))
AC = subset(dataE, grepl('ANTICOAGULANTS', dataE$drug_class))
dim(AC)
```
#P-value
```{r AD_AC, echo=FALSE}

pat_p = table(AD$patient_key, AD$pdc_80_flag)
p = chisq.test(pat_p); p

pat_pa = table(AC$patient_key, AC$pdc_80_flag)
pa = chisq.test(pat_pa); pa
```
```{r age_group1, echo= FALSE}
group44 = subset(AD, grepl('2', AD$age_grpN))
g44 = table(group44$age_grpN, group44$pdc_80_flag)
chisq.test(g44)

age44 = table(AD$age_grpN, AD$pdc_80_flag)
chisq.test(age44)

groupAC44 = subset(AC, grepl('2', AC$age_grpN))
gAC44 = table(groupAC44$age_grpN, groupAC44$pdc_80_flag)
chisq.test(gAC44)

```
```{r age_group, echo= FALSE}
group64 = subset(AD, grepl('3', AD$age_grpN))
g64 = table(group64$age_grpN, group64$pdc_80_flag)
chisq.test(g64)



groupAC64 = subset(AC, grepl('3', AC$age_grpN))
gAC64 = table(groupAC64$age_grpN, groupAC64$pdc_80_flag)
chisq.test(gAC64)

```
```{r age_group2, echo= FALSE}
group64 = subset(AD, grepl('3', AD$age_grpN))
g64 = table(group64$age_grpN, group64$pdc_80_flag)
chisq.test(g64)

groupAC64 = subset(AC, grepl('3', AC$age_grpN))
gAC64 = table(groupAC64$age_grpN, groupAC64$pdc_80_flag)
chisq.test(gAC64)

group65 = subset(AD, grepl('4', AD$age_grpN))
g65 = table(group65$age_grpN, group65$pdc_80_flag)
chisq.test(g65)

groupAC65 = subset(AC, grepl('4', AC$age_grpN))
gAC65 = table(groupAC65$age_grpN, groupAC65$pdc_80_flag)
chisq.test(gAC65)
```
```{r gender, echo= FALSE}
male = subset(AD, grepl('1', AD$sexN))
mAD = table(male$sexN, male$pdc_80_flag)
chisq.test(mAD)

man = subset(AC, grepl('1', AC$sexN))
mAC = table(man$sexN, man$pdc_80_flag)
chisq.test(mAC)
```
```{r regionN, echo=FALSE}
AD_1 = subset(AD, grepl('1', AD$regionN))
AD_NE = table(AD_1$regionN, AD_1$pdc_80_flag)
chisq.test(AD_NE)

AC_1 = subset(AC, grepl('1', AC$regionN))
AC_NE = table(AC_1$regionN, AC_1$pdc_80_flag)
chisq.test(AC_NE)

AD_2 = subset(AD, grepl('2', AD$regionN))
AD_MW = table(AD_2$regionN, AD_2$pdc_80_flag)
chisq.test(AD_MW)

AC_2 = subset(AC, grepl('2', AC$regionN))
AC_MW = table(AC_2$regionN, AC_2$pdc_80_flag)
chisq.test(AC_MW)

AD_3 = subset(AD, grepl('3', AD$regionN))
AD_S = table(AD_3$regionN, AD_3$pdc_80_flag)
chisq.test(AD_S)

AC_3 = subset(AC, grepl('3', AC$regionN))
AC_S = table(AC_3$regionN, AC_3$pdc_80_flag)
chisq.test(AC_S)

AD_4 = subset(AD, grepl('4', AD$regionN))
AD_N = table(AD_4$regionN, AD_4$pdc_80_flag)
chisq.test(AD_N)

AC_4 = subset(AC, grepl('4', AC$regionN))
AC_N = table(AC_4$regionN, AC_4$pdc_80_flag)
chisq.test(AC_N)
```
```{r ALCOHOL, echo=FALSE}

AD_A = subset(AD, grepl('1', AD$ALCOHOL_DRUG))
AD_AL = table(AD_A$ALCOHOL_DRUG, AD_A$pdc_80_flag)
chisq.test(AD_AL)

AC_A = subset(AC, grepl('1', AC$ALCOHOL_DRUG))
AC_AL = table(AC_A$ALCOHOL_DRUG, AC_A$pdc_80_flag)
chisq.test(AC_AL)
```


```{r ASTHMA, echo=FALSE}

AD_as = subset(AD, grepl('1', AD$ASTHMA))
AD_AS = table(AD_as$ASTHMA, AD_as$pdc_80_flag)
chisq.test(AD_AS)

AC_as = subset(AC, grepl('1', AC$ASTHMA))
AC_AS = table(AC_as$ASTHMA, AC_as$pdc_80_flag)
chisq.test(AC_AS)
```
```{r CARDIAC_ARRYTHMIA2, echo=FALSE}

AD_ar = subset(AD, grepl('1', AD$CARDIAC_ARRYTHMIA))
AD_AR = table(AD_ar$CARDIAC_ARRYTHMIA, AD_ar$pdc_80_flag)
chisq.test(AD_AR)

AC_ar = subset(AC, grepl('1', AC$CARDIAC_ARRYTHMIA))
AC_AR = table(AC_ar$CARDIAC_ARRYTHMIA, AC_ar$pdc_80_flag)
chisq.test(AC_AR)
```
```{r CARDIAC_VALVULAR, echo=FALSE}

AD_cv = subset(AD, grepl('1', AD$CARDIAC_VALVULAR))
AD_CV = table(AD_cv$CARDIAC_VALVULAR, AD_cv$pdc_80_flag)
chisq.test(AD_CV)

AC_cv = subset(AC, grepl('1', AC$CARDIAC_VALVULAR))
AC_CV = table(AC_cv$CARDIAC_VALVULAR, AC_cv$pdc_80_flag)
chisq.test(AC_CV)
```
```{r CEREBROVASCULAR, echo=FALSE}

AD_cv = subset(AD, grepl('1', AD$CEREBROVASCULAR))
AD_CV = table(AD_cv$CEREBROVASCULAR, AD_cv$pdc_80_flag)
chisq.test(AD_CV)

AC_ce = subset(AC, grepl('1', AC$CEREBROVASCULAR))
AC_CE = table(AC_ce$CEREBROVASCULAR, AC_ce$pdc_80_flag)
chisq.test(AC_CE)
```
```{r CHRONIC_KIDNEY, echo=FALSE}

AD_ck = subset(AD, grepl('1', AD$CHRONIC_KIDNEY))
AD_CK = table(AD_ck$CHRONIC_KIDNEY, AD_ck$pdc_80_flag)
chisq.test(AD_CK)

AC_ck = subset(AC, grepl('1', AC$CHRONIC_KIDNEY))
AC_CK = table(AC_ck$CHRONIC_KIDNEY, AC_ck$pdc_80_flag)
chisq.test(AC_CK)
```
```{r CHRONIC_PAIN_FIBRO, echo=FALSE}

AD_cp = subset(AD, grepl('1', AD$CHRONIC_PAIN_FIBRO))
AD_CP = table(AD_cp$CHRONIC_PAIN_FIBRO, AD_cp$pdc_80_flag)
chisq.test(AD_CP)

AC_cp = subset(AC, grepl('1', AC$CHRONIC_PAIN_FIBRO))
AC_CP = table(AC_cp$CHRONIC_PAIN_FIBRO, AC_cp$pdc_80_flag)
chisq.test(AC_CP)
```
```{r CHF, echo=FALSE}

AD_chf = subset(AD, grepl('1', AD$CHF))
AD_CHF = table(AD_chf$CHF, AD_chf$pdc_80_flag)
chisq.test(AD_CHF)

AC_chf = subset(AC, grepl('1', AC$CHF))
AC_CHF = table(AC_chf$CHF, AC_chf$pdc_80_flag)
chisq.test(AC_CHF)
```
```{r COPD, echo=FALSE}

AD_c = subset(AD, grepl('1', AD$COPD))
AD_COPD = table(AD_c$COPD, AD_c$pdc_80_flag)
chisq.test(AD_COPD)

AC_c = subset(AC, grepl('1', AC$COPD))
AC_COPD = table(AC_c$COPD, AC_c$pdc_80_flag)
chisq.test(AC_COPD)
```
```{r DEMENTIA, echo=FALSE}

AD_d = subset(AD, grepl('1', AD$DEMENTIA))
AD_D = table(AD_d$DEMENTIA, AD_d$pdc_80_flag)
#chisq.test(AD_D)

AC_d = subset(AC, grepl('1', AC$DEMENTIA))
AC_D = table(AC_d$DEMENTIA, AC_d$pdc_80_flag)
chisq.test(AC_D)
```
```{r DEPRESSION, echo=FALSE}

AD_dr = subset(AD, grepl('1', AD$DEPRESSION))
AD_DR= table(AD_dr$DEPRESSION, AD_dr$pdc_80_flag)
chisq.test(AD_DR)

AC_dr = subset(AC, grepl('1', AC$DEPRESSION))
AC_DR = table(AC_dr$DEPRESSION, AC_dr$pdc_80_flag)
chisq.test(AC_DR)
```
```{r DIABETES, echo=FALSE}

AD_di = subset(AD, grepl('1', AD$DIABETES))
AD_DI= table(AD_di$DIABETES, AD_di$pdc_80_flag)
chisq.test(AD_DI)

AC_di = subset(AC, grepl('1', AC$DIABETES))
AC_DI = table(AC_di$DIABETES, AC_di$pdc_80_flag)
chisq.test(AC_DI)
```
```{r DYSLIPIDEMIA, echo=FALSE}

AD_dy = subset(AD, grepl('1', AD$DYSLIPIDEMIA))
AD_DY= table(AD_dy$DYSLIPIDEMIA, AD_dy$pdc_80_flag)
chisq.test(AD_DY)

AC_dy = subset(AC, grepl('1', AC$DYSLIPIDEMIA))
AC_DY = table(AC_dy$DYSLIPIDEMIA, AC_dy$pdc_80_flag)
chisq.test(AC_DY)
```
```{r EPILEPSY_SEIZURE, echo=FALSE}

AD_es = subset(AD, grepl('1', AD$EPILEPSY_SEIZURE))
AD_ES= table(AD_es$EPILEPSY_SEIZURE, AD_es$pdc_80_flag)
chisq.test(AD_ES)

AC_es = subset(AC, grepl('1', AC$EPILEPSY_SEIZURE))
AC_ES = table(AC_es$EPILEPSY_SEIZURE, AC_es$pdc_80_flag)
chisq.test(AC_ES)
```
```{r HEPATITIS, echo=FALSE}

AD_h = subset(AD, grepl('1', AD$HEPATITIS))
AD_H= table(AD_h$HEPATITIS, AD_h$pdc_80_flag)
chisq.test(AD_H)

AC_h = subset(AC, grepl('1', AC$HEPATITIS))
AC_H = table(AC_h$HEPATITIS, AC_h$pdc_80_flag)
chisq.test(AC_H)
```
```{r HIV_AIDS, echo=FALSE}

AD_hiv = subset(AD, grepl('1', AD$HIV_AIDS))
AD_HIV= table(AD_hiv$HIV_AIDS, AD_hiv$pdc_80_flag)
chisq.test(AD_HIV)

AC_hiv = subset(AC, grepl('1', AC$HIV_AIDS))
AC_HIV = table(AC_hiv$HIV_AIDS, AC_hiv$pdc_80_flag)
chisq.test(AC_HIV)
```
```{r HYPERTENSION, echo=FALSE}

AD_hy = subset(AD, grepl('1', AD$HYPERTENSION))
AD_HY= table(AD_hy$HYPERTENSION, AD_hy$pdc_80_flag)
chisq.test(AD_HY)

AC_hy = subset(AC, grepl('1', AC$HYPERTENSION))
AC_HY = table(AC_hy$HYPERTENSION, AC_hy$pdc_80_flag)
chisq.test(AC_HY)
```
```{r LIVER_GALLBLADDER_PANCREAS, echo=FALSE}

AD_gp = subset(AD, grepl('1', AD$LIVER_GALLBLADDER_PANCREAS))
AD_GP= table(AD_gp$LIVER_GALLBLADDER_PANCREAS, AD_gp$pdc_80_flag)
chisq.test(AD_GP)

AC_gp = subset(AC, grepl('1', AC$LIVER_GALLBLADDER_PANCREAS))
AC_GP = table(AC_gp$LIVER_GALLBLADDER_PANCREAS, AC_gp$pdc_80_flag)
chisq.test(AC_GP)
```
```{r MI_CAD, echo=FALSE}

AD_cad = subset(AD, grepl('1', AD$MI_CAD))
AD_CAD= table(AD_cad$MI_CAD, AD_cad$pdc_80_flag)
chisq.test(AD_CAD)

AC_cad = subset(AC, grepl('1', AC$MI_CAD))
AC_CAD = table(AC_cad$MI_CAD, AC_cad$pdc_80_flag)
chisq.test(AC_CAD)
```
```{r OSTEOARTHRITIS, echo=FALSE}

AD_o = subset(AD, grepl('1', AD$OSTEOARTHRITIS))
AD_O= table(AD_o$OSTEOARTHRITIS, AD_o$pdc_80_flag)
chisq.test(AD_O)

AC_o = subset(AC, grepl('1', AC$OSTEOARTHRITIS))
AC_O = table(AC_o$OSTEOARTHRITIS, AC_o$pdc_80_flag)
chisq.test(AC_O)
```
```{r PARALYSIS, echo=FALSE}

AD_p = subset(AD, grepl('1', AD$PARALYSIS))
AD_P= table(AD_p$PARALYSIS, AD_p$pdc_80_flag)
chisq.test(AD_P)

AC_p = subset(AC, grepl('1', AC$PARALYSIS))
AC_P = table(AC_p$PARALYSIS, AC_p$pdc_80_flag)

```
```{r PEPTIC_ULCER, echo=FALSE}

AD_pu = subset(AD, grepl('1', AD$PEPTIC_ULCER))
AD_PU= table(AD_pu$PEPTIC_ULCER, AD_pu$pdc_80_flag)
chisq.test(AD_PU)

AC_pu = subset(AC, grepl('1', AC$PEPTIC_ULCER))
AC_PU = table(AC_pu$PEPTIC_ULCER, AC_pu$pdc_80_flag)
chisq.test(AC_PU)
```
```{r PERIPHERAL_VASCULAR, echo=FALSE}

AD_pv = subset(AD, grepl('1', AD$PERIPHERAL_VASCULAR))
AD_PV= table(AD_pv$PERIPHERAL_VASCULAR, AD_pv$pdc_80_flag)
chisq.test(AD_PV)

AC_pv = subset(AC, grepl('1', AC$PERIPHERAL_VASCULAR))
AC_PV = table(AC_pv$PERIPHERAL_VASCULAR, AC_pv$pdc_80_flag)
chisq.test(AC_PV)
```
```{r RENAL_FAILURE, echo=FALSE}

AD_rf = subset(AD, grepl('1', AD$RENAL_FAILURE))
AD_RF= table(AD_rf$RENAL_FAILURE, AD_rf$pdc_80_flag)
chisq.test(AD_RF)

AC_rf = subset(AC, grepl('1', AC$RENAL_FAILURE))
AC_RF = table(AC_rf$RENAL_FAILURE, AC_rf$pdc_80_flag)
chisq.test(AC_RF)
```
```{r RHEUMATOLOGIC, echo=FALSE}

AD_r = subset(AD, grepl('1', AD$RHEUMATOLOGIC))
AD_R= table(AD_r$RHEUMATOLOGIC, AD_r$pdc_80_flag)
chisq.test(AD_R)

AC_r = subset(AC, grepl('1', AC$RHEUMATOLOGIC))
AC_R = table(AC_r$RHEUMATOLOGIC, AC_r$pdc_80_flag)
chisq.test(AC_R)
```
```{r SCHIZOPHRENIA, echo=FALSE}

AD_s = subset(AD, grepl('1', AD$SCHIZOPHRENIA))
AD_S= table(AD_s$SCHIZOPHRENIA, AD_s$pdc_80_flag)
#chisq.test(AD_S)

AC_s = subset(AC, grepl('1', AC$SCHIZOPHRENIA))
AC_S = table(AC_s$SCHIZOPHRENIA, AC_s$pdc_80_flag)
#chisq.test(AC_S)
```
```{r SLEEP_DISORDERS, echo=FALSE}

AD_sd = subset(AD, grepl('1', AD$SLEEP_DISORDERS))
AD_SD= table(AD_sd$SLEEP_DISORDERS, AD_sd$pdc_80_flag)
chisq.test(AD_SD)

AC_sd = subset(AC, grepl('1', AC$SLEEP_DISORDERS))
AC_SD = table(AC_sd$SLEEP_DISORDERS, AC_sd$pdc_80_flag)
chisq.test(AC_SD)
```
```{r SMOKING, echo=FALSE}

AD_so = subset(AD, grepl('1', AD$SMOKING))
AD_SO= table(AD_so$SMOKING, AD_so$pdc_80_flag)
chisq.test(AD_SO)

AC_so = subset(AC, grepl('1', AC$SMOKING))
AC_SO = table(AC_so$SMOKING, AC_so$pdc_80_flag)
chisq.test(AC_SO)
```
```{r THYROID, echo=FALSE}

AD_t = subset(AD, grepl('1', AD$THYROID))
AD_T= table(AD_t$THYROID, AD_t$pdc_80_flag)
chisq.test(AD_T)

AC_t = subset(AC, grepl('1', AC$THYROID))
AC_T = table(AC_t$THYROID, AC_t$pdc_80_flag)
chisq.test(AC_T)
```
```{r Solid_Tumor, echo=FALSE}

AD_st = subset(AD, grepl('1', AD$Solid_Tumor))
AD_ST= table(AD_st$Solid_Tumor, AD_st$pdc_80_flag)
chisq.test(AD_ST)

AC_st = subset(AC, grepl('1', AC$Solid_Tumor))
AC_ST = table(AC_st$Solid_Tumor, AC_st$pdc_80_flag)
chisq.test(AC_ST)
```
```{r Metastatic, echo=FALSE}

AD_m = subset(AD, grepl('1', AD$Metastatic))
AD_M= table(AD_m$Metastatic, AD_m$pdc_80_flag)
chisq.test(AD_M)

AC_m = subset(AC, grepl('1', AC$Metastatic))
AC_M = table(AC_m$Metastatic, AC_m$pdc_80_flag)
chisq.test(AC_M)
```
```{r Leukemia_Lymphoma, echo=FALSE}

AD_l = subset(AD, grepl('1', AD$Leukemia_Lymphoma))
AD_L= table(AD_l$Leukemia_Lymphoma, AD_l$pdc_80_flag)
chisq.test(AD_L)

AC_l = subset(AC, grepl('1', AC$Leukemia_Lymphoma))
AC_L= table(AC_l$Leukemia_Lymphoma, AC_l$pdc_80_flag)
chisq.test(AC_L)
```
```{r Other_Cancer, echo=FALSE}

AD_oc = subset(AD, grepl('1', AD$Other_Cancer))
AD_OC= table(AD_oc$Other_Cancer, AD_oc$pdc_80_flag)
chisq.test(AD_OC)

AC_oc = subset(AC, grepl('1', AC$Other_Cancer))
AC_OC= table(AC_oc$Other_Cancer, AC_oc$pdc_80_flag)
chisq.test(AC_OC)
```
```{r pre_ip_flag, echo=FALSE}

AD_pr = subset(AD, grepl('1', AD$pre_ip_flag))
AD_PR= table(AD_pr$pre_ip_flag, AD_pr$pdc_80_flag)
chisq.test(AD_PR)

AC_pr = subset(AC, grepl('1', AC$pre_ip_flag))
AC_PR= table(AC_pr$pre_ip_flag, AC_pr$pdc_80_flag)
chisq.test(AC_PR)
```
```{r num_op, echo=FALSE}


AD_OP= table(AD$num_op, AD$pdc_80_flag)
chisq.test(AD_OP)


AC_OP= table(AC$num_op, AC$pdc_80_flag)
chisq.test(AC_OP)
```
```{r pre_er_flag, echo=FALSE}

AD_er = subset(AD, grepl('1', AD$pre_er_flag))
AD_ER= table(AD_er$pre_er_flag, AD_er$pdc_80_flag)
chisq.test(AD_ER)

AC_er = subset(AC, grepl('1', AC$pre_er_flag))
AC_ER= table(AC_er$pre_er_flag, AC_er$pdc_80_flag)
chisq.test(AC_ER)
```
```{r post_ip_flag, echo=FALSE}

AD_pip = subset(AD, grepl('1', AD$post_ip_flag))
AD_Pip= table(AD_pip$post_ip_flag, AD_pip$pdc_80_flag)
chisq.test(AD_Pip)

AC_pip = subset(AC, grepl('1', AC$post_ip_flag))
AC_Pip= table(AC_pip$post_ip_flag, AC_pip$pdc_80_flag)
chisq.test(AC_Pip)
```
```{r num_op_post, echo=FALSE}


AD_Pop= table(AD$num_op_post, AD$pdc_80_flag)
chisq.test(AD_Pop)


AC_POp= table(AC$num_op_post, AC$pdc_80_flag)
chisq.test(AC_POp)
```
```{r post_er_flag, echo=FALSE}

AD_per = subset(AD, grepl('1', AD$post_er_flag))
AD_PER= table(AD_per$post_er_flag, AD_per$pdc_80_flag)
chisq.test(AD_PER)

AC_per = subset(AC, grepl('1', AC$post_er_flag))
AC_PER= table(AC_per$post_er_flag, AC_per$pdc_80_flag)
chisq.test(AC_PER)
```

```{r post_total_cost, echo= FALSE}
dataE$post_total_cost = as.numeric(dataE$post_total_cost)
dataE$pdc_80_flag = as.numeric(dataE$pdc_80_flag)
boxplot(dataE$post_total_cost, dataE$pdc_80_flag)
post_AD_c = subset(AD, select = c('patient_key','pdc_80_flag', 'post_total_cost'))
post_AD_c$post_total_cost = as.numeric(post_AD_c$post_total_cost)
Post_AD_r = post_AD_c %>% group_by(patient_key, pdc_80_flag, post_total_cost) %>% summarise( total= sum(as.numeric(post_total_cost)))
Post_AD_r$total %>% median
Post_AD_r$total %>% sd

post_AC_c = subset(AC, select = c('patient_key','pdc_80_flag', 'post_total_cost'))
post_AC_c$post_total_cost = as.numeric(post_AC_c$post_total_cost)
Post_AC_r = post_AC_c %>% group_by(patient_key, pdc_80_flag, post_total_cost) %>% summarise( total= sum(as.numeric(post_total_cost)))
Post_AC_r$total %>% median
Post_AC_r$total %>% sd

post_cost_p = t.test(post_AD_c$post_total_cost ~ post_AD_c$pdc_80_flag, mu = 2546.899 , alternative = 'two.sided', conf= 0.95, var.eq = FALSE) 
#OR!
post_cost_pp = t.test(post_AD_c$post_total_cost[post_AD_c$pdc_80_flag == '0'], post_AD_c$post_total_cost[post_AD_c$pdc_80_flag == '1'])

var(post_AD_c$post_total_cost[post_AD_c$pdc_80_flag == '0'])
var(post_AD_c$post_total_cost[post_AD_c$pdc_80_flag == '1'])
#AC
post_cost_ac = t.test(post_AC_c$post_total_cost ~ post_AC_c$pdc_80_flag, mu = 6166.107, alternative = 'two.sided', conf= 0.95, var.eq = FALSE) 
#AC
post_cost_acc = t.test(post_AC_c$post_total_cost[post_AC_c$pdc_80_flag == '0'], post_AC_c$post_total_cost[post_AC_c$pdc_80_flag == '1'])
#because the value is less than 0.05 we reject the null. reject that there is no diff between mean lung capacity between smokers and nonsmokers.

var(post_AC_c$post_total_cost[post_AC_c$pdc_80_flag == '0'])
var(post_AC_c$post_total_cost[post_AC_c$pdc_80_flag == '1'])

```
